name: create changeset for PR created by Renovate

on:
  pull_request:
    branches:
      - main

jobs:
  default:
    runs-on: ubuntu-latest
    # commit author should be renovate[bot]
    if: startsWith(github.head_ref, 'renovate/') && github.event.pull_request.user.login == 'renovate[bot]' && github.actor == 'renovate[bot]'
    steps:
      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          token: ${{ steps.app-token.outputs.token }}
      - uses: ./.github/actions/setup
        with:
          token: ${{ steps.app-token.outputs.token }}
          bot-app-slug: ${{ steps.app-token.outputs.app-slug }}
      - uses: YutaUra/actions/renovate-changeset@7a9f6f2289b30c72ea4e27a3bf32c383af68d51f # v0.0.92
        with:
          token: ${{ steps.app-token.outputs.token }}
          setup-git-user: false
