name: check_PR

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          token: ${{ steps.app-token.outputs.token }}
      - uses: ./.github/actions/setup
        with:
          token: ${{ steps.app-token.outputs.token }}
          bot-app-slug: ${{ steps.app-token.outputs.app-slug }}

      - uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3 # v4.9.1
        with:
          distribution: "temurin"
          java-version: "17"

      - run: pnpm install
      - run: pnpm exec biome check --fix

      - uses: int128/update-generated-files-action@821b0e0f25930c953a1a66e48d71bf0ae6ab15b3 # v2.107.0
        if: always()
        with:
          token: ${{ steps.app-token.outputs.token }}
