name: wait-for-workflows

on:
  pull_request:

jobs:
  wait-for-workflows:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: int128/wait-for-workflows-action@ad8c6b767dc32b6b7a83fe9b6ce2f537d4a9e9de # v1.50.0
        with:
          token: ${{ steps.app-token.outputs.token }}
